require("__base__.prototypes.entity.pipecovers")
local hit_effects = require("__base__.prototypes.entity.hit-effects")
local sounds = require("__base__.prototypes.entity.sounds")

data:extend({
	{
		type = "item",
		name = "diesel-miner",
		icon = "__diesel_machines__/graphics/diesel-miner/diesel-miner-icon-64.png",
		icon_size = 64,
		subgroup = "extraction-machine",
		order = "a[items]-c[diesel-miner]",
		place_result = "diesel-miner",
		stack_size = 20,
		weight = 200 * kg,
	},
})
data:extend({
	{
		type = "mining-drill",
		name = "diesel-miner",
		icon = "__diesel_machines__/graphics/diesel-miner/diesel-miner-icon-64.png",
		icon_size = 64,
		flags = { "placeable-neutral", "player-creation" },
		minable = { mining_time = 0.5, result = "diesel-miner" },
		max_health = 1000,
		resource_categories = { "basic-solid", "hard-solid" },
		corpse = "diesel-miner-remnants",
		dying_explosion = "big-mining-drill-explosion",
		collision_box = { { -3.35, -3.35 }, { 3.35, 3.35 } },
		selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
		drawing_box_vertical_extension = 1,
		damaged_trigger_effect = hit_effects.entity(),
		diesel_fuel_fluid_filter = true,
		energy_source = {
			type = "fluid",
			burns_fluid = true,
			scale_fluid_usage = true,
			fluid_box = {
				volume = 500,
				pipe_covers = pipecoverspictures(),
				pipe_picture = diesel_miner_pipepictures(),
				pipe_connections = {
					{ direction = defines.direction.west, position = { -3, -2 } },
					{ direction = defines.direction.west, position = { -3, 2 } },
					{ direction = defines.direction.east, position = { 3, -2 } },
					{ direction = defines.direction.east, position = { 3, 2 } },
				},
			},
			smoke = {
				{
					name = "smoke",
					frequency = 20,
					north_position = { 3.0, -4.3 },
					south_position = { 3.0, -4.3 },
					east_position = { 3.0, -4.3 },
					west_position = { 3.0, -4.3 },
					starting_vertical_speed = 0.08,
					starting_frame_deviation = 60,
				},
			},
			emissions_per_minute = { pollution = 100 },
		},
		energy_usage = "3MW",
		input_fluid_box = {
			volume = 200,
			pipe_covers = pipecoverspictures(),
			pipe_picture = diesel_miner_pipepictures(),
			pipe_connections = {
				{ direction = defines.direction.west, position = { -3, 0 } },
				{ direction = defines.direction.east, position = { 3, 0 } },
			},
		},

		mining_speed = 5.0,
		resource_searching_radius = 9.49,
		radius_visualisation_picture = {
			filename = "__space-age__/graphics/entity/big-mining-drill/big-mining-drill-radius-visualization.png",
			width = 10,
			height = 10,
		},
		monitor_visualization_tint = { r = 78, g = 173, b = 255 },
		vector_to_place_result = { 0, -3.85 },
		module_slots = 5,

		--resource_drain_rate_percent = 50,
		drops_full_belt_stacks = true,
		perceived_performance = { maximum = 30.0 },
		--fast_replaceable_group = "big-mining-drill",

		circuit_connector = table.deepcopy(circuit_connector_definitions["big-mining-drill"]),
		circuit_wire_max_distance = default_circuit_wire_max_distance,

		working_sound = {
			main_sounds = {
				sound = {
					filename = "__space-age__/sound/entity/big-mining-drill/big-mining-drill-working-loop.ogg",
					--volume = 0.3,
					volume = 0.5,
				},
				fade_in_ticks = 4,
				fade_out_ticks = 30,
			},
			max_sounds_per_prototype = 1,
		},
		open_sound = sounds.drill_open,
		close_sound = sounds.drill_close,

		graphics_set = {
			animation = {
				north = {
					layers = {
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-spritesheet.png",
							priority = "high",
							width = 576,
							height = 576,
							frame_count = 32,
							line_length = 8,
							shift = util.by_pixel(0, 0),
							scale = 0.5,
						},
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-shadow.png",
							priority = "high",
							width = 768,
							height = 768,
							frame_count = 1,
							repeat_count = 32,
							draw_as_shadow = true,
							shift = util.by_pixel(0, 0),
							scale = 0.5,
						},
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-output-N.png",
							priority = "high",
							width = 256,
							height = 256,
							frame_count = 1,
							repeat_count = 32,
							shift = util.by_pixel(0, -80),
							scale = 0.5,
						},
					},
				},
				east = {
					layers = {
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-spritesheet.png",
							priority = "high",
							width = 576,
							height = 576,
							frame_count = 32,
							line_length = 8,
							shift = util.by_pixel(0, 0),
							scale = 0.5,
						},
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-shadow.png",
							priority = "high",
							width = 768,
							height = 768,
							frame_count = 1,
							repeat_count = 32,
							draw_as_shadow = true,
							shift = util.by_pixel(0, 0),
							scale = 0.5,
						},
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-output-E.png",
							priority = "high",
							width = 256,
							height = 256,
							frame_count = 1,
							repeat_count = 32,
							shift = util.by_pixel(80, 0),
							scale = 0.5,
						},
					},
				},
				south = {
					layers = {
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-spritesheet.png",
							priority = "high",
							width = 576,
							height = 576,
							frame_count = 32,
							line_length = 8,
							shift = util.by_pixel(0, 0),
							scale = 0.5,
						},
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-shadow.png",
							priority = "high",
							width = 768,
							height = 768,
							frame_count = 1,
							repeat_count = 32,
							draw_as_shadow = true,
							shift = util.by_pixel(0, 0),
							scale = 0.5,
						},
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-output-S.png",
							priority = "high",
							width = 256,
							height = 256,
							frame_count = 1,
							repeat_count = 32,
							shift = util.by_pixel(0, 80),
							scale = 0.5,
						},
					},
				},
				west = {
					layers = {
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-spritesheet.png",
							priority = "high",
							width = 576,
							height = 576,
							frame_count = 32,
							line_length = 8,
							shift = util.by_pixel(0, 0),
							scale = 0.5,
						},
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-shadow.png",
							priority = "high",
							width = 768,
							height = 768,
							frame_count = 1,
							repeat_count = 32,
							draw_as_shadow = true,
							shift = util.by_pixel(0, 0),
							scale = 0.5,
						},
						{
							filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-output-W.png",
							priority = "high",
							width = 256,
							height = 256,
							frame_count = 1,
							repeat_count = 32,
							shift = util.by_pixel(-80, 0),
							scale = 0.5,
						},
					},
				},
			},
		},
	},
	{
		type = "corpse",
		name = "diesel-miner-remnants",
		hidden = true,
		icon = "__diesel_machines__/graphics/diesel-miner/diesel-miner-icon-64.png",
		icon_size = 64,
		flags = { "placeable-neutral", "not-on-map" },
		subgroup = "extraction-machine-remnants",
		order = "a-a-a",
		selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
		tile_width = 7,
		tile_height = 7,
		selectable_in_game = false,
		time_before_removed = 60 * 60 * 15,
		expires = false,
		final_render_layer = "remnants",
		remove_on_tile_placement = false,
		animation = {
			filename = "__diesel_machines__/graphics/diesel-miner/diesel-miner-remnants.png",
			width = 576,
			height = 576,
			scale = 0.5,
			direction_count = 1,
		},
	},
})
